services:
  - type: web
    name: yosuf-flask-docker-app
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    autoDeploy: true